version: '2.3'

services:
  app:
    image: application
    runtime: nvidia
    pid: "host"
    ports:
      - 5010:5000
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace/app
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    # command: waitress-serve --port=5010 backend:app

  bot:
    image: bot
    runtime: nvidia
    pid: "host"
    ports:
      - 5011:5000
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace/bot
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    # command: python telebot/bot.py

volumes:
  cv:
  bot: